# Generated by Django 6.0.5 on 2026-05-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
