# Generated by Django 6.0.5 on 2026-05-08 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_bank_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(blank=True, max_length=255)),
                ("business_description", models.TextField(blank=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="seller_profiles/"
                    ),
                ),
                ("instagram_handle", models.CharField(blank=True, max_length=100)),
                ("whatsapp_number", models.CharField(blank=True, max_length=15)),
                ("twitter_handle", models.CharField(blank=True, max_length=100)),
                ("website_url", models.URLField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("total_deals", models.PositiveIntegerField(default=0)),
                ("completed_deals", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
