services:
  - type: web
    name: trustpay-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: FRONTEND_URL
        value: https://trust-pay-frontend.vercel.app
      - key: PAYAZA_MOCK_MODE
        value: True
