# Generated by Django 6.0.5 on 2026-05-07 23:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("buyer_email", models.EmailField(blank=True, max_length=254)),
                ("buyer_phone", models.CharField(blank=True, max_length=15)),
                ("item_description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("delivery_days", models.PositiveIntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("PAID", "Paid"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("COMPLETED", "Completed"),
                            ("DISPUTED", "Disputed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING_PAYMENT",
                        max_length=20,
                    ),
                ),
                ("va_account_number", models.CharField(blank=True, max_length=20)),
                ("va_bank_name", models.CharField(blank=True, max_length=100)),
                (
                    "va_reference",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("auto_release_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trust_fee_percent",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESOLVED_REFUND", "Resolved - Refund"),
                            ("RESOLVED_RELEASE", "Resolved - Release"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("COLLECTION", "Collection"),
                            ("PAYOUT", "Payout"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payaza_ref", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
