# Generated by Django 6.0.5 on 2026-05-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0003_alter_deal_va_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="buyer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="deal",
            name="delivery_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
